import { BookT } from './book.types'

export const dummies: BookT[] = [
  {
    id: 1,
    title: 'Harry Potter und der Halbblut Prinz',
    ean: '1234',
    content: 'Test',
    price: 11.11,
  },
  {
    id: 2,
    title: 'Der Herr der Ringe',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 3,
    title: 'Der Hobbit',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 4,
    title: 'Das Café am Rande der Welt',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 5,
    title: 'Harry Potter und der Halbblut Prinz',
    ean: '1234',
    content: 'Test',
    price: 11.11,
  },
  {
    id: 6,
    title: 'Der Herr der Ringe 2',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 7,
    title: 'Der Hobbit 2',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 8,
    title: 'Das Café am Rande der Welt 2',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 9,
    title: 'Harry Potter und der Halbblut Prinz 2',
    ean: '1234',
    content: 'Test',
    price: 11.11,
  },
  {
    id: 10,
    title: 'Der Herr der Ringe 3',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 11,
    title: 'Der Hobbit 3',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
  {
    id: 12,
    title: 'Das Café am Rande der Welt 3',
    ean: '12345',
    content: 'Test 2',
    price: 12.11,
  },
]
